# Generated by Django 4.1.2 on 2022-11-07 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPlayground', '0002_cajonera_escritorio_mesaluz_delete_nobel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cajonera',
            name='cajones',
        ),
    ]
