# Generated by Django 4.1.2 on 2022-11-22 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPlayground', '0005_alter_jugador_nacimiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cajonera',
        ),
        migrations.DeleteModel(
            name='Escritorio',
        ),
        migrations.DeleteModel(
            name='Mesaluz',
        ),
    ]
