# Generated by Django 4.1.2 on 2022-11-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPlayground', '0007_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='s1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='s10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='s11',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='s12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='s13',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='s14',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='s15',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='s16',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='s17',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='s18',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='s2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='s3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='s4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='s5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='s6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='s7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='s8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='s9',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha',
            field=models.DateField(default=0),
        ),
    ]
