# Generated by Django 4.1.2 on 2022-11-22 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPlayground', '0008_tarjeta_s1_tarjeta_s10_tarjeta_s11_tarjeta_s12_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='score',
        ),
    ]
